### ISSUE TITLE
Move all processing to ortfo/portfoliomk

### ISSUE THREAD

**Issue by gwennlbh** [gwennlbh/portfolio-v6#85]
- [ ] A way to handle nested `extends` (cannot fix nested extends
    statements, that's why 404.pug and 500.pug are 'disabled')
- [ ] General localization, not hardcoded `[]string{"fr", "en"}`.
- [ ] Choosable locations for `src/`, `dist/`, `mixins/` and `layouts/`
- [ ] Special handling for `mixins/` and `layouts/`, i.e:
  - [ ] do not render their file as regular pages,
  - [ ] do not include their folders in `dist/`
  - [ ] consider all `include` and `extends` statements without leading `./`
  or `/` to be relative to `layouts/`
